### ISSUE TITLE
module doesn't seem to accept that Class::AccessorMaker is installed, though it is.

### ISSUE THREAD

**Issue by andersje** [ccin2p3/puppet-cpan#18]
I believe the issue lies within the ruby check for inappropriate perl exit code:

   #cpan doesn't always provide the right exit code, so we double check
    system("perl #{ll} -M#{resource[:name]} -e1 > /dev/null 2>&1")
    estatus = $?.exitstatus

with Class::AccessorMaker, because if you call Class::AccessorMaker with that, you'll always get an exit code 255 -- even though it's installed properly.

Is this actually an issue with the AccessorMaker cpan module?

**Comment by salimane** [comment]
@andersje are you still having a problem when you use the latest version of the module at https://forge.puppet.com/meltwater/cpan

**Comment by faxm0dem** [comment]
This is fixed in master:

```cpan { 'Class::AccessorMaker':
  ensure          => present,
  exists_strategy => 'find',
}
```
