### ISSUE TITLE
Should be able to add environment variables

### ISSUE THREAD

**Issue by jsmelser** [ccin2p3/puppet-cpan#47]
I need to set and environment variable for DB2 perl module to install. It would be nice if I could just add something like environment => 'DB2_HOME=<DIR>' and the module sets it right before trying to install the module.

**Comment by faxm0dem** [comment]
is this required at install time?
isn't it sufficient at runtime to set DB2_HOME?

**Comment by faxm0dem** [comment]
apparently it is :)
can you test the f/env-vars branch and tell me if it works for you?

**Comment by jsmelser** [comment]
You are wonderful my friend. Thanks for getting on this so quickly:

  cpan { 'Bundle::DBD::DB2':
    ensure      => present,
    environment => {
      'DB2_HOME'        => '/opt/ibm/server/db2/V10.5/',
      'LD_LIBRARY_PATH' => '$LD_LIBRARY_PATH:/opt/ibm/server/db2/V10.5/lib64/',
    },
  }

PERL_DL_NONLAZY=1 /usr/bin/perl "-Iblib/lib" "-Iblib/arch" test.pl
Name "DBI::dbi_debug" used only once: possible typo at test.pl line 21.
1..5
ok 1
ok 2
ok 3
ok 4
ok 5
make[1]: Entering directory `/root/.cpan/build/DBD-DB2-1.85-v8D3SZ/Constants'
No tests defined for DBD::DB2::Constants extension.
make[1]: Leaving directory `/root/.cpan/build/DBD-DB2-1.85-v8D3SZ/Constants'
  IBMTORDB2/DBD-DB2-1.85.tar.gz
  /usr/bin/make test -- OK
Running make install
Prepending /root/.cpan/build/DBD-DB2-1.85-v8D3SZ/blib/arch /root/.cpan/build/DBD-DB2-1.85-v8D3SZ/blib/lib to PERL5LIB for 'install'
make[1]: Entering directory `/root/.cpan/build/DBD-DB2-1.85-v8D3SZ/Constants'
make[1]: Leaving directory `/root/.cpan/build/DBD-DB2-1.85-v8D3SZ/Constants'
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Installing /usr/local/lib64/perl5/auto/DBD/DB2/DB2.so
Installing /usr/local/lib64/perl5/auto/DBD/DB2/DB2.bs
Installing /usr/local/lib64/perl5/auto/DBD/DB2/Constants/Constants.so
Installing /usr/local/lib64/perl5/auto/DBD/DB2/Constants/Constants.bs
Installing /usr/local/lib64/perl5/DBD/DB2.pm
Installing /usr/local/lib64/perl5/DBD/DB2.pod
Installing /usr/local/lib64/perl5/DBD/DB2/Constants.pm
Installing /usr/local/lib64/perl5/auto/DBD/DB2/Constants/autosplit.ix
Installing /usr/local/lib64/perl5/Bundle/DBD/DB2.pm
Installing /usr/local/share/man/man3/Bundle::DBD::DB2.3pm
Installing /usr/local/share/man/man3/DBD::DB2.3pm
Appending installation info to /usr/lib64/perl5/perllocal.pod
  IBMTORDB2/DBD-DB2-1.85.tar.gz
  /usr/bin/make install  -- OK
Notice: Applied catalog in 103.33 seconds
