### ISSUE TITLE
Notice: /Stage[main]/Cpan::Install/Package[perl-CPAN]/ensure: current_value 'purged', should be 'present'

### ISSUE THREAD

**Issue by brentclark** [ccin2p3/puppet-cpan#52]
Good day

I get this message

Notice: /Stage[main]/Cpan::Install/Package[perl-CPAN]/ensure: current_value 'purged', should be 'present'

Running Debian Stretch

There is no package called perl-cpan in any Debian release.

https://packages.debian.org/search?keywords=perl-cpan&searchon=names&suite=all&section=all

**Comment by faxm0dem** [comment]
this has been solved. please reopen if I'm mistaken
