### ISSUE TITLE
No parameter named 'environment'

### ISSUE THREAD

**Issue by maoneal** [ccin2p3/puppet-cpan#61]
After downloading the code from here, and installing it directly on our Puppet server (necessary, since your updated code actually pays attention to environmentally set proxy variables we are using) -- I'm getting an error randomly on a client server, and not sure what in the code could be causing it.  This is the Puppet code snippet I'm using:

`        ## CPAN Packages
        class { '::cpan':
                manage_package => false,
        }
        cpan { 'DBD::Oracle':
                ensure          => present,
                environment     => {
                        'ORACLE_HOME'     => '/oracleHomes/product/19.0.0/client_1',
                        'LD_LIBRARY_PATH' => '/oracleHomes/product/19.0.0/client_1/lib',  
                },
                exists_strategy => 'find',
                require         => Class['::cpan'],
        }
        ## End of CPAN Packages
`

Works fine, installs the CPAN module, usually runs correctly when executing 'puppet agent -t'

Periodically (every 5 or 6) runs, it will start throwing errors:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'environment' `

This will often continue to throw an error for the next 5 or 6 runs, then clear up, and then start again another 5 or 6 runs down the line.  I'm frankly baffled as to what could be causing it.

**Comment by faxm0dem** [comment]
Hi, sorry for the delay - I'm looking at this as we speak

**Comment by faxm0dem** [comment]
Do you only have one puppet master ?

**Comment by maoneal** [comment]
No worries -- only a single Puppet master, yes.

**Comment by faxm0dem** [comment]
This is really odd. It rings an old bell with a bug we had with the server cache.
Could you restart the puppet master ?
Other thing to check : maybe try to reproduce using `puppet apply`.

**Comment by maoneal** [comment]
I ended up (finally!) having an opportunity do a full restart of our Puppet Master server, and I've been testing this quite a bit today, and I haven't been able to reproduce the error.  Sorry for the false alert, and thank you for your guidance!
